apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: viken-no

resources:
  - ../../../base

commonLabels:
  app.kubernetes.io/instance: fint-flyt-discovery-service_viken_no
  fintlabs.no/org-id: viken.no

patches:
  - patch: |-
      - op: replace
        path: "/spec/kafka/acls/0/topic"
        value: "viken-no.flyt.*"
      - op: replace
        path: "/spec/orgId"
        value: "viken.no"
      - op: replace
        path: "/spec/url/basePath"
        value: "/beta/viken-no"
      - op: replace
        path: "/spec/ingress/basePath"
        value: "/beta/viken-no/api/intern/metadata"
      - op: replace
        path: "/spec/env/1/value"
        value: "{\"viken.no\":[\"https://role-catalog.vigoiks.no/vigo/flyt/user\"],\"vigo.no\":[\"https://role-catalog.vigoiks.no/vigo/flyt/developer\"]}"

    target:
      kind: Application
      name: fint-flyt-discovery-service

