apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: agderfk-no

resources:
  - ../../../base

commonLabels:
  app.kubernetes.io/instance: fint-flyt-discovery-service_agderfk_no
  fintlabs.no/org-id: agderfk.no

patches:
  - patch: |-
      - op: replace
        path: "/spec/kafka/acls/0/topic"
        value: "agderfk-no.flyt.*"
      - op: replace
        path: "/spec/orgId"
        value: "agderfk.no"
      - op: replace
        path: "/spec/url/basePath"
        value: "/beta/agderfk-no"
      - op: replace
        path: "/spec/ingress/basePath"
        value: "/beta/agderfk-no/api/intern/metadata"
      - op: replace
        path: "/spec/env/1/value"
        value: "agderfk.no, vigo.no"

    target:
      kind: Application
      name: fint-flyt-discovery-service

