apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: aiven-kafka
spec:
  itemPath: "vaults/aks-alpha-vault/items/aiven-kafka"
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: viken-no-fint-flyt-discovery-service
spec:
  itemPath: "vaults/aks-alpha-vault/items/viken-no-fint-flyt-discovery-service"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: fint-flyt-discovery-service
  name: fint-flyt-discovery-service
spec:
  ports:
    - port: 8080
  type: ClusterIP
  selector:
    io.kompose.service: fint-flyt-discovery-service
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: fint-flyt-discovery-service
  labels:
    app: fint-flyt-discovery-service
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`viken-no-skjema.vigoiks.no`) && PathPrefix(`/api/intern/metadata`)
      kind: Rule
      services:
        - name: fint-flyt-discovery-service
          port: 8080
      middlewares:
        - name: fint-flyt-auth-forward
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    io.kompose.service: fint-flyt-discovery-service
  name: fint-flyt-discovery-service
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      io.kompose.service: fint-flyt-discovery-service
  template:
    metadata:
      labels:
        io.kompose.service: fint-flyt-discovery-service
    spec:
      restartPolicy: Always
      volumes:
        - name: credentials
          secret:
            secretName: aiven-kafka-certificates
      containers:
        - image: fintlabsacr.azurecr.io/fint-flyt-discovery-service:dummy
          name: fint-flyt-discovery-service
          volumeMounts:
            - name: credentials
              mountPath: /credentials
          resources:
            limits:
              memory: "2048Mi"
              cpu: "1"
            requests:
              memory: "512Mi"
              cpu: "100m"
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: aiven-kafka
            - secretRef:
                name: viken-no-fint-flyt-discovery-service
          env:
            - { name: TZ, value: Europe/Oslo }
            - { name: JAVA_TOOL_OPTIONS, value: '-XX:+ExitOnOutOfMemoryError -Xmx1840M' }
            - { name: logging.level.no.fintlabs.arkiv, value: info }
            - { name: fint.org-id, value: 'viken.no' }
            - { name: spring.datasource.hikari.schema, value: 'viken_no' }
            - { name: fint.flyt.resource-server.security.api.internal.enabled, value: 'true' }
            - { name: fint.flyt.resource-server.security.api.internal.authorized-org-ids, value: 'viken.no, vigo.no' }