version: 2
updates:
    - package-ecosystem: gradle
      directory: "/"
      schedule:
          interval: weekly
          day: wednesday
          time: "04:30"
          timezone: "Europe/Oslo"
      open-pull-requests-limit: 10
      labels:
          - dependencies
          - backend
      groups:
          spring:
              patterns:
                  - "org.springframework*"
          kotlin:
              patterns:
                  - "org.jetbrains.kotlin*"
          minor-and-patch:
              patterns:
                  - "*"
              update-types:
                  - minor
                  - patch
      ignore:
          - dependency-name: "org.springframework*"
            update-types:
                - "version-update:semver-major"
    - package-ecosystem: github-actions
      directory: "/"
      schedule:
          interval: weekly
          day: monday
          time: "04:30"
          timezone: "Europe/Oslo"
      labels:
          - dependencies
          - github-actions
