version: 2
updates:
    - package-ecosystem: gradle
      directory: "/"
      schedule:
          interval: weekly
          day: wednesday
          time: "04:30"
          timezone: "Europe/Oslo"
      open-pull-requests-limit: 10
      groups:
          spring:
              patterns:
                  - "org.springframework*"
          kotlin:
              patterns:
                  - "*kotlin*"
          minor-and-patch:
              patterns:
                  - "*"
              update-types:
                  - minor
                  - patch
      ignore:
          - dependency-name: "org.springframework*"
            update-types:
                - "version-update:semver-major"
