fint:
  org-id: fintlabs.no
  flyt:
    resource-server:
      security:
        api:
          external:
            enabled: true
            authorized-client-ids: 1
          internal:
            enabled: true
            authorized-org-ids: viken.no, vigo.no
  kafka:
    default-replicas: 1
spring:
  kafka:
    bootstrap-servers: localhost:9092
  datasource:
    hikari:
      schema: fintlabs_no
    url: jdbc:postgresql://localhost:5437/fint-flyt-discovery-service
    username: postgres
    password: password

  webflux:
    base-path: vlfk-no
server:
  port: 8084




